### ISSUE TITLE
State Query

### ISSUE THREAD

**Issue by kappe** [vmwareairwatchsdk/vmware-wsone-sdk-reactnative#11]
@akalghatgi is there a way to query state like "queryDeviceEnrollmentStatus" or "jailBrokenStatus"?

**Comment by akalghatgi** [comment]
@kappe we have an api to check if Device is "IsCompromised"... but not DeviceEnrollmentStatus... We are taking note of it...

Thanks & Regards,
Amit

**Comment by kappe** [comment]
accidentally closed. waiting for integration ;-)

**Comment by akalghatgi** [comment]
API isEnrolled available in latest 1.3.0
