### ISSUE TITLE
Issue within example code

### ISSUE THREAD

**Issue by kappe** [vmwareairwatchsdk/vmware-wsone-sdk-reactnative#12]
@Maddy79 in https://github.com/vmwareairwatchsdk/vmware-wsone-sdk-reactnative/blob/master/GettingStarted.md
You show the following example:
Usage
import WorkspaceOneSdk from 'react-native-workspace-one-sdk';
import { NativeModules} from 'react-native';
const {WorkspaceOneSdk } = NativeModules;

this example is faulty because WorkspaceOneSdk ist declared twice

**Comment by akalghatgi** [comment]
@kappe Code doesn't have multiple declaration, it is in the documentation.... we are rectifying it. 
Thanks for pointing out.

Regards,
Amit

**Comment by kappe** [comment]
@kappe yes - only in docu!

have a nice weekend

Harry
