### ISSUE TITLE
HUB does not redirect to App

### ISSUE THREAD

**Issue by kappe** [vmwareairwatchsdk/vmware-wsone-sdk-reactnative#14]
@akalghatgi Hi Amit, unfortunately I've a new problem:

1. Building the App is successful
2. App starts on the device
3. HUB starts up
4. Authentication
4. HUB configuration (progress bar appears)
5. But now HUB does not redirect to the App. Instead the HUB shows the account page with my credentials. At the top of this page a link back to my App is shown.
6. When I click on the link, an error message is shown: Unable to request configuration  

Best Regards

Harry

**Comment by akalghatgi** [comment]
@kappe can you check LSApplicationQueriesSchemes entry in plist? if this is not configured correctly it will not re-direct.

Regards,
Amit

**Comment by kappe** [comment]
@akalghatgi I've checked it already:
<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>AWSSOBroker2</string>
		<string>awbs</string>
		<string>awb</string>
		<string>wsonesdk</string>
		<string>awws1enroll</string>
		<string>airwatch</string>
	</array>

Regards,

Harry

**Comment by akalghatgi** [comment]
@kappe can you confirm this if you have added in AppDelegate?


Add following code in AppDelegate

```
-(BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  //Add following code for posting Notification for URL
  NSNotification *info = [[NSNotification alloc]initWithName:@"UIApplicationOpenURLOptionsSourceApplicationKey" object:url userInfo:options];
  [[NSNotificationCenter defaultCenter] postNotification:info];
  
  return YES;
}
```

**Comment by kappe** [comment]
@akalghatgi YES
```
-(BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
// *** for testing I've added the following line - no improvement ***/
  BOOL retval= [[AWController clientInstance] handleOpenURL:url fromApplication:@"blub"];
  NSNotification *info = [[NSNotification alloc]initWithName:@"UIApplicationOpenURLOptionsSourceApplicationKey" object:url userInfo:options];
  [[NSNotificationCenter defaultCenter] postNotification:info];
  return YES;
}
```

**Comment by akalghatgi** [comment]
Can you confirm **CFBundleURLSchemes** in plist.... you can refer [GettingStarted](https://github.com/vmwareairwatchsdk/vmware-wsone-sdk-reactnative/blob/master/GettingStarted.md)
Add Callback Scheme Registration Step 6.

For reference check the example plist.
 [example plist](https://github.com/vmwareairwatchsdk/vmware-wsone-sdk-reactnative/blob/master/ios/example/Info.plist)
```
<key>CFBundleURLTypes</key>
  <array>
    <dict>
      <key>CFBundleURLName</key>
      <string>com.air-watch.WorkspaceOne.Example.iOS</string>
      <key>CFBundleURLSchemes</key>
      <array>
        <string>wsoexample</string>
      </array>
      <key>URL types</key>
      <string>Editor</string>
    </dict>
  </array>
</dict>
```

Regards,
Amit

**Comment by kappe** [comment]
@akalghatgi my version:
`<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>com.baypol.ppm.zeusmobile</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>zeusmobile</string>
			</array>
		</dict>
	</array>
`
Regards,
Harry

**Comment by kappe** [comment]
@akalghatgi my version:
`<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>com.baypol.ppm.zeusmobile</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>zeusmobile</string>
			</array>
		</dict>
	</array>
`

Regards,
Harry

**Comment by kappe** [comment]
@akalghatgi my version:
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>com.baypol.ppm.zeusmobile</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>zeusmobile</string>
			</array>
		</dict>
	</array>

Regards,
Harry

**Comment by kappe** [comment]
@akalghatgi my version:
`<key>CFBundleURLTypes</key> 

	<array>
		<dict>

			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>com.baypol.ppm.zeusmobile</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>zeusmobile</string>
			</array>
		</dict>

	</array>
`
Regards,
Harry

**Comment by kappe** [comment]
@akalghatgi my version:

`
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>com.baypol.ppm.zeusmobile</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>zeusmobile</string>
			</array>
		</dict>
	</array>

`
Regards,
Harry

**Comment by kappe** [comment]
@akalghatgi my version:
`<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>com.baypol.ppm.zeusmobile</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>zeusmobile</string>
			</array>
		</dict>
	</array>
`
Regards,
Harry

**Comment by kappe** [comment]
@akalghatgi The version of an older Version (without using ws1-sdk-react-native):
`<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>zeusmobile</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>zeusmobile</string>
			</array>
		</dict>
	</array>`

**Comment by akalghatgi** [comment]
@kappe try adding this

```
-(BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{

  [AWController clientInstance].callbackScheme = @"zeusmobile";
  NSNotification *info = [[NSNotification alloc]initWithName:@"UIApplicationOpenURLOptionsSourceApplicationKey" object:url userInfo:options];
  [[NSNotificationCenter defaultCenter] postNotification:info];
  return YES;
}
```
Regards,
Amit

**Comment by kappe** [comment]
@akalghatgi unfortunately no. my current settings:

`<key>CFBundleURLTypes</key>
        <array>
                <dict>
                        <key>CFBundleTypeRole</key>
                        <string>Editor</string>
                        <key>CFBundleURLName</key>
                        <string>com.airwatch.sdk</string>
                        <key>CFBundleURLSchemes</key>
                        <array>
                                <string>zeusmobile</string>
                        </array>
                </dict>
        </array>
`
Harry

**Comment by akalghatgi** [comment]
@kappe can you try this workaround...
```
-(BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  //set callback scheme
  [AWController clientInstance].callbackScheme = @"zeusmobile";
  NSNotification *info = [[NSNotification alloc]initWithName:@"UIApplicationOpenURLOptionsSourceApplicationKey" object:url userInfo:options];
  [[NSNotificationCenter defaultCenter] postNotification:info];
  return YES;
}
```

regards,
Amit

**Comment by kappe** [comment]
@akalghatgi Hi Amit,
this is my Info.plist entry:
`<key>CFBundleURLTypes</key>
        <array>
                <dict>
                        <key>CFBundleTypeRole</key>
                        <string>Editor</string>
                        <key>CFBundleURLName</key>
                        <string>com.baypol.ppm.zeusmobile</string>
                        <key>CFBundleURLSchemes</key>
                        <array>
                                <string>zeusmobile</string>
                        </array>
                </dict>
        </array>
`
and this the patched function:
`-(BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  [AWController clientInstance].callbackScheme = @"com.baypol.ppm.zeusmobile";
  NSNotification *info = [[NSNotification alloc]initWithName:@"UIApplicationOpenURLOptionsSourceApplicationKey" object:url userInfo:options];
  [[NSNotificationCenter defaultCenter] postNotification:info];
  return YES;
}`

no improvement.

Regards,
Harry

**Comment by akalghatgi** [comment]
@kappe change the `[AWController clientInstance].callbackScheme = @"com.baypol.ppm.zeusmobile";` to `[AWController clientInstance].callbackScheme = @"zeusmobile";`

**Comment by kappe** [comment]
@akalghatgi current settings - no improvements. (I also tried CFBundleURLName set to zeusmobile)
`-(BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  [AWController clientInstance].callbackScheme = @"zeusmobile";
  NSNotification *info = [[NSNotification alloc]initWithName:@"UIApplicationOpenURLOptionsSourceApplicationKey" object:url userInfo:options];
  [[NSNotificationCenter defaultCenter] postNotification:info];
  return YES;
}`
------------------
`<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>com.baypol.ppm.zeusmobile</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>zeusmobile</string>
			</array>
		</dict>
	</array>`

**Comment by akalghatgi** [comment]
@kappe kindly check with following entry in plist`<key>CFBundleURLSchemes</key> <array> <string> wsoexample </string> </array>` we are checking from our end why it is failing for custom values.

regards,
Amit

**Comment by kappe** [comment]
@akalghatgi today I did a complete new setup of my project. I get back to You tomorrow ...
Regards,
Harry

**Comment by kappe** [comment]
@akalghatgi Hi Amit, new setup is ready:
I once more compared Info.plist from the example and of my project. I found the following diffs:

1. example Info.plist has the following entry:
`<key>AWAppIdentifierPrefix</key>
  <string>Z7N7QHVWT1.</string>`
my file doesn't a relevant entry

2. example Info.plist has the following entry:
`<key>CFBundleURLTypes</key>
  <array>
    <dict>
      <key>CFBundleURLName</key>
      <string>com.air-watch.WorkspaceOne.Example.iOS</string>
      <key>CFBundleURLSchemes</key>
      <array>
        <string>wsoexample</string>
      </array>
      **<key>URL types</key>
      <string>Editor</string>**
    </dict>
  </array>`

within my file it looks like this:
`<key>CFBundleURLTypes</key>
        <array>
                <dict>
                        <key>CFBundleTypeRole</key>
                        <string>Editor</string>
                        <key>CFBundleURLName</key>
                        <string>com.baypol.ppm.zeusmobile</string>
                        <key>CFBundleURLSchemes</key>
                        <array>
                                <string>zeusmobile</string>
                        </array>
                <key>URL types</key>
                    <string>Editor</string>
                </dict>
        </array>
`
I've added the option 'URL types'.  Within my file is an additional option 'CFBundleTypeRole'? I've switched this from 'Editor' to 'None' - no improvement. Still the same issue. I'm now updating the phone to iOS 15 ...

Regards,
Harry

**Comment by akalghatgi** [comment]
@kappe can change this section of plist from `<key>CFBundleURLSchemes</key> <array> <string>zeusmobile</string> </array>` to `<key>CFBundleURLSchemes</key> <array> <string>wsoexample</string>` 

Regards,
Amit.

**Comment by kappe** [comment]
@akalghatgi I've set `<key>CFBundleURLSchemes</key> <array> <string>wsoexample</string>` now the HUB does no longer switch to the "account page", it now switches to the page with gray circle with the white question mark inside!?

Additional Info: My iPhone 8 is now on iOS 15 and XCode on Version 13.

Regards,
Harry

**Comment by kappe** [comment]
@akalghatgi Hi Amit,
during App start I have 2 errors:
`2021-09-23 14:40:50.739522+0200 mZeus21[428:20356] [javascript] Running "mZeus21" with {"rootTag":1,"initialProps":{}}
2021-09-23 14:40:50.741149+0200 mZeus21[428:20509] (ConsoleLogger.cpp.64) stacktrace: code: 900502, domain: com.vmware.xsw.settings.attributes, error: Attribute is unavailable to Attribute Provider (line 128) {}
    at [anon] (/Users/bamboo/bamboo-agent-home/xml-data/build-dir/SDK-ISLA3087-FWK112/airwatchsdk/Pods/XSWChameleon/util/logger/ConsoleLogger.cpp:53) internal
    at error () native strict preventsyield
    at [anon] (js/error.js:18) preventsyield
    at [anon] () native strict preventsyield
    at asm_get (eval:1) tailcall
    at getPayloadForProductId (eval:222)
    at storeJsonPayload (eval:137)
    at eval (eval:2) preventsyield
2021-09-23 14:40:50.741351+0200 mZeus21[428:20509] (ChameleonContext.cpp.173) eval failed
2021-09-23 14:40:50.741527+0200 mZeus21[428:20509] (DuktapeUtil.h.26) error: Error: code: 900502, domain: com.vmware.xsw.settings.attributes, error: Attribute is unavailable to Attribute Provider (line 128)
    at [anon] (/Users/bamboo/bamboo-agent-home/xml-data/build-dir/SDK-ISLA3087-FWK112/airwatchsdk/Pods/XSWChameleon/app/module/capi/CInteropAppModule.cpp:128) internal
    at [anon] () native strict preventsyield
    at asm_get (eval:1) tailcall
    at getPayloadForProductId (eval:222)
    at storeJsonPayload (eval:137)
    at eval (eval:2) preventsyield
2021-09-23 14:40:50:744 20516 [I] (CoreOperationalDataProvider.cpp.236) payload generator version: 2.3.0e [com.air-watch.sdk.main ApplicationSettings+Setup:56]`

Do You have any new informations for me?

Regards,
Harry

**Comment by kappe** [comment]
@akalghatgi Hi Amit,
are there any new Informations? My Project is still pausing!?
Regards,
Harry

**Comment by akalghatgi** [comment]
Please integrate latest 1.3.0 version...

**Comment by kappe** [comment]
@akalghatgi version 1.3.0 does **not** fix the problem!
still same behavior ...

Regards,
Harry

**Comment by akalghatgi** [comment]
@kappe please verify your plist entry... you can configure `CFBundleURLSchemes ` only  rest you should keep as is below.

```
<key>CFBundleURLTypes</key>
  <array>
    <dict>
      <key>CFBundleURLName</key>
      <string>com.airwatch.sdk</string>
      <key>CFBundleURLSchemes</key>
      <array>
        <string>zeusmobile</string>
      </array>
      <key>URL types</key>
      <string>Editor</string>
    </dict>
  </array>
</dict>
```

Regards,
Amit

**Comment by kappe** [comment]
@akalghatgi looks like this. when I switch wsoexample to zeusmobile I'm getting the problem ...
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>com.baypol.ppm.zeusmobile</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>wsoexample</string>
			</array>
			<key>URL types</key>
			<string>Editor</string>
		</dict>
	</array>

**Comment by amitrkalghatgi** [comment]
@kappe change CFBundleURLName to com.airwatch.SDK and try... you can change schemename to any you wish... 

Regards 
Amit

**Comment by kappe** [comment]
@akalghatgi 
this parameter **are not working:**
```
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>com.airwatch.SDK</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>zeusmobile</string>
			</array>
			<key>URL types</key>
			<string>Editor</string>
		</dict>
	</array>

```
this parameter **are working:**
```
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>com.airwatch.SDK</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>wsoexample</string>
			</array>
			<key>URL types</key>
			<string>Editor</string>
		</dict>
	</array>
```

**Comment by amitrkalghatgi** [comment]
@kappe my bad please change com.airwatch.SDK to com.airwatch.sdk 

<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>com.airwatch.sdk</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>zeusmobile</string>
			</array>
			<key>URL types</key>
			<string>Editor</string>
		</dict>
	</array>

**Comment by kappe** [comment]
@amitrkalghatgi my current parameters:
no redirect to the app!
```
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>com.airwatch.sdk</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>zeusmobile</string>
			</array>
			<key>URL types</key>
			<string>Editor</string>
		</dict>
	</array>
```

**Comment by kappe** [comment]
@amitrkalghatgi 
killing the hub and switching back to _wsoexample_  and recompiling the app, the redirect is working again.

Regards,
Harry
