### ISSUE TITLE
WorkspaceOneSdk.swift => No such module 'AWSDK'

### ISSUE THREAD

**Issue by kappe** [vmwareairwatchsdk/vmware-wsone-sdk-reactnative#8]
Hi,

after npm install ...
and pod install 
(both works fine) 
I'm getting an error during compilation:  WorkspaceOneSdk.swift  => no such module 'AWSDK' 

Best regards

Harry

**Comment by akalghatgi** [comment]
@kappe can you please share the Pod install logs.. also npm install ... logs.

Regards,
Amit

**Comment by kappe** [comment]
Hi Amit,

Project setup: 
npx create-react-native-app --use-npm tstApp
------------------------
expo install ws1-sdk-react-native
Installing 1 other package using npm.
> npm install --save ws1-sdk-react-native
+ ws1-sdk-react-native@1.1.0
added 1 package from 1 contributor and audited 1022 packages in 5.592s

27 packages are looking for funding
  run `npm fund` for details

found 8 vulnerabilities (6 low, 2 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
-----------------------------------------------
 pod install
Installing unimodules:
 expo-application@3.2.0 from ../node_modules/expo-application/ios
 expo-constants@11.0.2 from ../node_modules/expo-constants/ios
 expo-error-recovery@2.2.0 from ../node_modules/expo-error-recovery/ios
 expo-file-system@11.1.3 from ../node_modules/expo-file-system/ios
 expo-font@9.2.1 from ../node_modules/expo-font/ios
 expo-image-loader@2.2.0 from ../node_modules/expo-image-loader/ios
 expo-keep-awake@9.2.0 from ../node_modules/expo-keep-awake/ios
 expo-modules-core@0.2.0 from ../node_modules/expo-modules-core/ios
 expo-splash-screen@0.11.4 from ../node_modules/expo-splash-screen/ios
 expo-structured-headers@1.1.1 from ../node_modules/expo-structured-headers/ios
 expo-updates@0.8.5 from ../node_modules/expo-updates/ios
 expo-updates-interface@0.2.2 from ../node_modules/expo-updates-interface/ios
 unimodules-app-loader@2.2.0 from ../node_modules/unimodules-app-loader/ios
 unimodules-core@7.1.2 from ../node_modules/@unimodules/core/ios
 unimodules-react-native-adapter@6.3.7 from ../node_modules/@unimodules/react-native-adapter/ios
 unimodules-task-manager-interface@6.2.0 from ../node_modules/unimodules-task-manager-interface/ios

Auto-linking React Native modules for target `zeusmobile21`: RNGestureHandler, RNReanimated, RNScreens, and ws1-sdk-react-native
Analyzing dependencies
Downloading dependencies
Installing ws1-sdk-react-native (1.1.0)
Generating Pods project
Integrating client project
Pod installation complete! There are 48 dependencies from the Podfile and 47 total pods installed.



Regards 

Harry

**Comment by akalghatgi** [comment]
@kappe installtion looks good... can you check in your PODS project if you can see AWSDK.acframework in Pods->Development Pods -> ws1-sdk-react-native -> Frameworks-> AWSDk.xcframework.

Thanks 
Amit

**Comment by kappe** [comment]
@akalghatgi yes, path exists and there is an entrie AWSDK.xcframework in folder Frameworks

Harry

**Comment by akalghatgi** [comment]
@kappe good... Can you please tell me about Xcode Version, and Device details on which you are trying to compile the tstApp on.

Regards,
Amit

**Comment by kappe** [comment]
@akalghatgi 
XCode Version: 12.5.1
Target: iPhone 8
iOS: 14.8
So far I didn't make any adaptions within info.plist and AppDelegate.m yet?!

**Comment by kappe** [comment]
@akalghatgi 
You can download the log file from here: https://kappe23.no-ip.org/build.log.gz
For this run I've used the simulator as target - throwing the same error

Harry

**Comment by akalghatgi** [comment]
@kappe not able to download the log.. can you paste it here...

Regards,
Amit

**Comment by kappe** [comment]
@akalghatgi 
[build.log.gz](https://github.com/vmwareairwatchsdk/vmware-wsone-sdk-reactnative/files/7169667/build.log.gz)

**Comment by kappe** [comment]
@akalghatgi 
<img width="1119" alt="Bildschirmfoto 2021-09-15 um 13 43 55" src="https://user-images.githubusercontent.com/394377/133427432-a39dcfac-586e-44ca-8f0a-fc7a333174d4.png">

**Comment by akalghatgi** [comment]
@kappe is your Mac with M1 chip?

**Comment by kappe** [comment]
@akalghatgi No. MacPro Core i7

**Comment by akalghatgi** [comment]
@kappe can you check if AWSDK.xcframework is present in this location "Users/kappe/mobile/mobTst/node_modules/ws1-sdk-react-native/iOS/"

**Comment by kappe** [comment]
@akalghatgi 
the path is /Users/kappe/mobile/mobTst/node_modules/ws1-sdk-react-native/**ios**
AWSDK.xcframework exists

**Comment by kappe** [comment]
@akalghatgi .../ios is completely lower case?!

**Comment by akalghatgi** [comment]
@kappe yes... just wanted to check AWSDK.xcframework is present or not... Can you try compiling this [Sample App](https://github.com/vmwareairwatchsdk/vmware-wsone-sdk-reactnative)... let see if there is any issue with template.

Thanks 
Amit

**Comment by kappe** [comment]
@akalghatgi compiling Your Sample App is throwing the same error

Showing All Errors Only
/Users/kappe/mobile/vmware-wsone-sdk-reactnative-master/node_modules/ws1-sdk-react-native/ios/WorkspaceOneSdk.swift:13:8: Module compiled with Swift 5.3.1 cannot be imported by the Swift 5.4.2 compiler: /Users/kappe/Library/Developer/Xcode/DerivedData/example-epmlilqxrmvovrdssrvnwtzxqfne/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/ws1-sdk-react-native/AWSDK.framework/Modules/AWSDK.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

**Comment by akalghatgi** [comment]
@kappe Nice... Downgrade your Xcode 12.3 as of now... we have a planned release for the above scenario.

Thanks 
Amit

**Comment by kappe** [comment]
@akalghatgi I found that on the web:
Build Libraries for Distribution option to Yes in your framework's build settings:
This ends up in your project.pbxproj file as:
BUILD_LIBRARY_FOR_DISTRIBUTION = YES;

Could not this be the solution?  Downgrading Xcode is not a good idea! There may be side effects within other projects!

Harry

**Comment by kappe** [comment]
@akalghatgi Can You provide a beta version of the planned release?
