### ISSUE TITLE
AWSDKDefaultSettings.plist 

### ISSUE THREAD

**Issue by kappe** [vmwareairwatchsdk/vmware-wsone-sdk-reactnative#9]
@akalghatgi Please tell me where to place AWSDKDefaultSettings.plist

**Comment by akalghatgi** [comment]
@kappe Create a AWSDKDefaultSettings.bundle with AWSDKDefaultSettings.plist in it and keep the bundle in ios app folder.

**Comment by kappe** [comment]
@akalghatgi thanks
